---
name: Tests
on:
  pull_request:
  push:
    branches: [devopsy]

env:
  AMI: ${{ secrets.AMI }}
  INST_NAME: goInstance
  INST_TYPE: t2.micro
  SEC_GRP_ID: ${{ secrets.SEC_GRP_ID }}
  SUBNET_ID: ${{ secrets.SUBNET_ID }}
  VOLUME_SIZE: 100
  PUB_IP: true
  AWS_DEFAULT_REGION: us-west-1

jobs:
  tests:
    name: Run tests - includes pre-commit hooks and determining code coverage %
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
        # TODO: Use the correct branch
      
      - name: Install python for pre-commit
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Install dependencies
        run: |
          brew install anaconda \
          black pylint shellfmt shellcheck

      - name: Setup tmate session
        #if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.1
        # Only report failures of pushes (PRs have are visible through the Checks section) 
        # to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          title: 🐛 Coverage report failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
